### ISSUE TITLE
range.parentContentControl  throw exception instead of null.

### ISSUE THREAD

**Issue by VimalKumarS** [OfficeDev/office-js-docs#422]
If selection doesn't have parent content control, following code throw error instead parentContentControl should be null as per documentation "Gets the content control that contains the range. Returns null if there isn't a parent content control. Read-only."

 var range = context.document.getSelection();
 var parentCC = range.parentContentControl;
 context.load(parentCC);

**Comment by mlafleur** [comment]
Hi Vimal, 

Could you provide the error message you are seeing?

**Comment by VimalKumarS** [comment]
hi,

Please find the error detail
for code i tried
let range = context.document.getSelection();
range.load('parentContentControl')
as per documentation it should result in null.
Error: {"name":"OfficeExtension.Error","code":"GeneralException","message":"GeneralException","traceMessages":[],"debugInfo":{"errorLocation":"Range.parentContentControl"},"stack":"GeneralException: GeneralException\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:19:182512)\n   at pi (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:19:197624)\n   at ht (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:19:197711)\n   at g (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:19:197531)\n   at l (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:19:196117)"}

-Vimal

**Comment by weshi** [comment]
Does this happen in Word Online or desktop client? We have a bug for Word Online to return null instead of throw general exception for such case. The bug for Word Online is already fixed and is rolling out to prod soon.

**Comment by VimalKumarS** [comment]
This is on desktop client both in Windows 10 and Mac osX.

**Comment by weshi** [comment]
Just to confirm, do you hit this issue in desktop client or Word Online?

**Comment by weshi** [comment]
Thanks Vimal. We will look into this issue. This should be a bug.

**Comment by weshi** [comment]
Vimal, this bug actually has already been fixed in desktop clients. Have you installed the latest Office updates for your clients? 

The fix for Word Online is already checked in, and is on its way rolling out to our Production environment.

**Comment by VimalKumarS** [comment]
Yes i have latest  word 2016 version 16.0.6965.2076 update
and over Mac i have word 16 15.24 (160709)

**Comment by weshi** [comment]
Confirmed that this has already been fixed (both for Desktop clients and Word Online). Please try the latest update and let us know if you still see any issues.

**Comment by VimalKumarS** [comment]
From where i get the updated js i am referring to 1.1, cdn path 
https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
using above .. it still show error

**Comment by mlafleur** [comment]
The proper CDN address is https://appsforoffice.microsoft.com/lib/1/hosted/office.js ("1/ " instead of "1.1/").  While they both seem to resolve to the same office.js version and is a long-shot, it may still be worth trying.

**Comment by VimalKumarS** [comment]
I tried again  i am still getting exception
Error: Error: {"name":"OfficeExtension.Error","code":"GeneralException","message":"GeneralException","traceMessages":[],"debugInfo":{"errorLocation":"Range.parentContentControl"},"stack":"GeneralException: GeneralException\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:19:189006)\n   at pi (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:19:211583)\n   at ht (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:19:211670)\n   at g (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:19:211490)\n   at l (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:19:210076)"}

Code i am using:
Word.run(function (context) {

            // Queue a command to get the current selection and then
            // create a proxy range object with the results.
            let range = context.document.getSelection();
            var ooxml = range.getOoxml();
            range.load('contentControls');

            return context.sync().then(function () {
                console.log(ooxml);
                console.log(range);
            });

        }).catch(function (error) {
            console.log('Error: ' + JSON.stringify(error));
            if (error instanceof OfficeExtension.Error) {
                console.log('Debug info: ' + JSON.stringify(error.debugInfo));
            }
            console.log(false)
        });

**Comment by VimalKumarS** [comment]
The following thing work for me using beta version
https://appsforoffice.microsoft.com/lib/beta/hosted/office.js 
can you please provide me the pointer from where can i access 1.2 preview version js.

**Comment by keyur32** [comment]
Hi @VimalKumarS, you can see the 1.3 Word Open Spec here: https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.3_Openspec

**Comment by Lauragra** [comment]
Closing this issue for now as it looks like it's resolved. Feel free to reopen if you have further questions. Thanks.

**Comment by KeyurPatel268** [comment]
Still issue persist in office 1.3 js with latest word update Microsoft Word 2016 MSO(16.0.6925.1049) 64 bit

**Comment by KeyurPatel268** [comment]
I can't get id of content control using parentContentControlOrNullObject method using beta CDN(office 1.3). Can you please guide me? I am using latest word version 1701 (build 7766.2060) 

  function insideOfContentControlCheck() {
        Word.run(function (ctx) {
            var myCC = ctx.document.getSelection().parentContentControlOrNullObject;
            ctx.load(myCC); // I think this is the part you are missing!
            return ctx.sync()
            .then(function () {
                if (myCC.id) {
                    console.log(myCC.title);// if there is a content control we'll show the title
                }
            });


        }).catch(function (e) {
            //there is no ContentControl.
            console.log("Error", e.message);

        });

    }

**Comment by Rick-Kirkham** [comment]
Before you test myCC.id, you have to test if myCC is null. You do that by checking if it has a "isNullObject" property set to true.
```
if (myCC.isNullObject) { //error handling}
else {
    console.log(myCC.title);// if there is a content control we'll show the title
}
```

**Comment by KeyurPatel268** [comment]
Thanks Rick. 
My Question is, I am not getting Inserted Content control ID.  It is always getting null after using parentContentControlOrNullObject method. How can i get content control ID. I am using beta CDN.
